config/routes.rb
Rails.application.routes.draw do
	require 'sidekiq/web'
	mount Sidekiq::Web, at: '/sidekiq'

  mount Base => '/api'
  
  root                               'static_pages#home'

  get  'user_profile'             => 'users#profile'
  
  get  'wechats/authorize'        => 'wechats#authorize'
  get  'wechats/wx_receive'       => 'wechats#wx_valid'
  post 'wechats/wx_receive'       => 'wechats#wx_receive'

  resources :records,                 only: [:index, :new]
  resources :users,                   only: [:index, :new, :create, :edit, :update]
end

app/views/layouts/_navbar.html.erb
<nav class="nav navbar-default navbar-static-top" style="background-color: #000000;">
  <div class="navbar-header">
     <button type="button" class="navbar-toggle" data-toggle="collapse"  data-target="#sidebar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
     </button>
     <a class="navbar-brand" href="#">Sencetime科技展</a>
  </div>
  <div class="collapse navbar-collapse" id="sidebar">
    <ul class="nav navbar-nav">
      <li><a href="<%= user_profile_path %>">个人信息</a></li>
      <li><a href="<%= new_user_path %>">编辑信息</a></li>
      <li><a href="<%= records_path %>">所有伙伴</a></li>
    </ul>
  </div> 
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WechatFaceSignin20160508</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>